const express = require("express");
const router = express.Router();
const verifyToken = require("../middleware/authMiddleware");
const authorizeRole = require("../middleware/roleMiddleware");
const { applyJob, getMyApplications, viewApplicants, acceptProposal, rejectProposal,withdrawApplication,checkApplication,getClientProposals } = require("../controllers/proposalController");
router.post("/apply/:jobId",verifyToken,authorizeRole("freelancer"),applyJob);
router.get("/my-applications",verifyToken,authorizeRole("freelancer"),getMyApplications);
router.delete("/:proposalId",verifyToken,withdrawApplication);
router.get("/applicants/:jobId",verifyToken,authorizeRole("client"),viewApplicants);
router.put("/accept/:id",verifyToken,authorizeRole("client"),acceptProposal);
router.put("/reject/:id",verifyToken,authorizeRole("client"),rejectProposal);
router.get("/client",verifyToken,authorizeRole("client"),getClientProposals);
router.get("/check/:jobId",verifyToken,checkApplication);
module.exports = router;