const express = require("express");
const router = express.Router();
const verifyToken = require("../middleware/authMiddleware");
const authorizeRole = require("../middleware/roleMiddleware");
const { applyJob, getMyApplications, viewApplicants, acceptProposal, rejectProposal } = require("../controllers/proposalController");
router.post("/apply/:jobId",verifyToken,authorizeRole("freelancer"),applyJob);
router.get("/my-applications",verifyToken,authorizeRole("freelancer"),getMyApplications);
router.get("/applicants/:jobId",verifyToken,authorizeRole("client"),viewApplicants);
router.put("/accept/:id",verifyToken,authorizeRole("client"),acceptProposal);
router.put("/reject/:id",verifyToken,authorizeRole("client"),rejectProposal);
module.exports = router;